### ISSUE TITLE
Running PutsReq in production through Docker

### ISSUE THREAD

**Issue by amotl** [phstc/putsreq#68]
Dear Pablo,

first things first: Thank you so much for conceiving and maintaining PutsReq. @thiasB started using it and now we would to ramp up a dedicated instance for our beehive monitoring project, see https://hiveeyes.org/ and https://community.hiveeyes.org/.

We need it to transform HTTP requests originating from [TTN](https://www.thethingsnetwork.org/) to converge properly to our data acquisition backend running [Kotori](https://getkotori.org/). @thiasB documented this specific telemetry path at [TTN/LoRaWAN setup for Terkin](https://github.com/hiveeyes/terkin-datalogger/tree/master/client/TTN), enjoy!

We have been able to get started with it already but humbly ask for further guidance to get things right.

With kind regards,
Andreas.

**Comment by amotl** [comment]
1. We started by building a Docker image and pushing it to https://hub.docker.com/u/daqzilla.
```
# Build
git clone https://github.com/phstc/putsreq
cd putsreq
docker build --tag daqzilla/putsreq:latest .

# Upload
docker login
docker push daqzilla/putsreq
```

2. Then, we amended the `docker-compose.yml` file like that to use that image. Please note we had to bump the MongoDB image version as the given thing just crashed silently on our Debian GNU/Linux 10 (buster) machine.
```
version: '3'
services:
  db:
    image: mongo:3.6.17
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
  redis:
    image: redis:alpine
  app:
    image: daqzilla/putsreq
    tty: true
    stdin_open: true
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '5050:3000'
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
```

3. Now, some links seem to point to `localhost` and we don't see any data from MongoDB under `./data` yet. There are just two empty directories:
```
l data/*
data/configdb:
total 0
drwxr-xr-x 2 root root  6 Apr 29 18:26 ./
drwxr-xr-x 4 root root 32 Apr 29 18:26 ../

data/db:
total 0
drwxr-xr-x 2 root root  6 Apr 29 18:26 ./
drwxr-xr-x 4 root root 32 Apr 29 18:26 ../
```
We had to adjust the `docker-compose.yml` because on the updated Docker image for MongoDB, there has apparently been no `/var/lib/mongo/data` directory.

**Comment by amotl** [comment]
Dear Pablo,

we see that "localhost" is referenced at different places within the source tree. Most probably because the Docker-based setup is primarily suited for development setups, right?

While we have seen [webpacker.yml](https://github.com/phstc/putsreq/blob/master/config/webpacker.yml) already, our knowledge is a bit limited on how to tune that or other files in order to compose an appropriate Docker image suitable to be run in production on a dedicated, full qualified hostname.

So, as mentioned above, we are humbly asking if you could support us to properly saddle up the pony.

Thanks already for taking the time and with kind regards,
Andreas.

**Comment by amotl** [comment]
We are now using this `docker-compose.yml`:
```
version: '3.6'
services:
  db:
    image: mongo:3.6.17
    tty: true
    stdin_open: true
    volumes:
      - data:/data/db
  redis:
    image: redis:alpine
  app:
    image: daqzilla/putsreq
    tty: true
    stdin_open: true
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - '5050:3000'
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
volumes:
  data:
    external:
      name: putsreq_mongodb
```

as well as this `.env.docker`:
```
RAILS_ENV=production
MONGOLAB_URI=mongodb://db
REDIS_URL=redis://redis
DEVISE_SECRET_KEY=PenyamJawnalg6
SECRET_TOKEN=eibWicDaBeOnucs
```

We also created the referenced external volume by invoking:
```
docker volume create --name=putsreq_mongodb
```

Additionally, the Docker image on https://hub.docker.com/r/daqzilla/putsreq has been amended like with the patch attached.

[putsreq-production.patch.txt](https://github.com/phstc/putsreq/files/4554757/putsreq-production.patch.txt)
